### ISSUE TITLE
Unit1_Week3_GitStarted_Review

### ISSUE THREAD

**Issue by johnakers** [tleung999/phase_0_unit_1#4]
Hi,

Everything you have done in this regard seems very thorough and I'm impressed.

It helps, particularly with git, to have a cheat sheet of sorts and yours definitely is helpful as you've sorted it.... in your workflow section... extremely well and articulated it properly. 

I'm sure you've investigated it but you can speed some things up. For instance, instead of:

git add [filename]

You can do:

git add *

This adds all the files that have been modified, though obviously it can have its faults if the proper precautions / care aren't taken.

There is also:

git commit -a "[message]"

Which adds AND commits a file in the same line.

Great job :)
- John

**Comment by tleung999** [comment]
Very Cool Jon with the commit -a.   I'll have to try it out on my next commit.   I am a big beginner with git.   I'd appreciate your feedback and input!
