### ISSUE TITLE
1_git_started 

### ISSUE THREAD

**Issue by dahal** [tleung999/phase_0_unit_1#5]
Hey @tleung999 ,

Your explanations are so simple to understand. Looks like you have solid understanding on git and git workflow. Keep up the good work. 

However, your .md files with commands and syntax might look better if you use correct syntax highlighting technique. Take a look at this image for example:-

![syntax](https://cloud.githubusercontent.com/assets/3684236/2940615/33c42af0-d988-11e3-8867-a9ed25d06061.jpg)

**Comment by tleung999** [comment]
Thanks Puru! I am horrible at md.    I see how you added syntax highlighting using ```.   Very nice.
